### ISSUE TITLE
Cannot interact with document with EM_ASM_xxx

### ISSUE THREAD

**Issue by system64MC** [yglukhov/jsbind#15]
Hi.

I want to pass a string or a seq of bytes with a length to a JavaScript function that downloads the file.
However, I can't interact with the DOM : it throws this error : 
```
Uncaught ReferenceError: document is not defined
    at 238071 (index.js:1314:36)
    at runEmAsmFunction (index.js:4615:31)
    at _emscripten_asm_const_int (index.js:4618:14)
    at download (index.wasm:0x8812d)
    at saveWav__synthesizerZexport70ile_u19(NimStringV2, int, bool) (index.wasm:0xcf6df)
    at saveWavWrapper__applicationZapp_u156(void*, void*) (index.wasm:0xd895f)
    at slave__pureZconcurrencyZthreadpool_u415(tyObject_Worker__AV8SPPeiKbtAJkcV6GYGBA*) (index.wasm:0xcfecd)
    at threadProcWrapDispatch__pureZconcurrencyZthreadpool_u547(tyObject_Thread__lJcYjCXoripf9c68yi9cXlAg*) (index.wasm:0x7dc79)
    at threadProcWrapStackFrame__pureZconcurrencyZthreadpool_u537(tyObject_Thread__lJcYjCXoripf9c68yi9cXlAg*) (index.wasm:0x7dcf2)
    at threadProcWrapper__pureZconcurrencyZthreadpool_u523(void*) (index.wasm:0x72581)
```
Is it normal? What can I do to fix this please?
This JS code triggers the issue : 
``var a = document.createElement('a');``

If possible, would it be possible to do a simple exemple?

Thanks for your help!

**Comment by yglukhov** [comment]
Judging from the stack trace, you're running this code in the worker thread, which doesn't have access to document? Hard to tell more without the source code.

**Comment by system64MC** [comment]
> Judging from the stack trace, you're running this code in the worker thread, which doesn't have access to document? Hard to tell more without the source code.

The main program calls this proc : 
```nim
proc download*(text: string) {.EMSCRIPTEN_KEEPALIVE.} =
        let str = text.cstring

        discard EM_ASM_INT("""
var element = document.createElement('a');
console.log(element);
//element.setAttribute('href', 'Download Btn');
//element.setAttribute('download', $0);

//element.style.display = 'none';

//window.body.appendChild(element);

//element.click();
//window.body.removeChild(element);
""", str)
```

**Comment by yglukhov** [comment]
Again, `download` is called from a thread, judging from your stack trace. The thread doesn't have access to `document`. Hard to tell more without **complete** source code.

**Comment by system64MC** [comment]
> Again, `download` is called from a thread, judging from your stack trace. The thread doesn't have access to `document`. Hard to tell more without **complete** source code.

Alright so, we have the main loop here : 
```nim
proc emMainLoop() {.cdecl.} =
    if(window.windowShouldClose):
        # saveState()
        igOpenGL3Shutdown()
        igGlfwShutdown()
        context.igDestroyContext()

        window.destroyWindow()
        nglfw.terminate()
        quit(0)
    nglfw.pollEvents()
    igOpenGL3NewFrame()
    igGlfwNewFrame()
    igNewFrame()

    case synthMode:
    of NONE:
        drawSelector()
    of KURUMI_X:
        # discard
        drawApp()
    of KURUMI_3:
        drawKurumi()

    igRender()

    glClearColor(0.45f, 0.55f, 0.60f, 1.00f)
    glClear(GL_COLOR_BUFFER_BIT)

    igOpenGL3RenderDrawData(igGetDrawData())

    window.swapBuffers()
    nglfw.swapInterval(1)

emscripten_set_main_loop(emMainLoop, 0, true)
```

Somewhere, I do this when a menu is selected : 
```nim
                 if(igBeginMenu(".WAV")):
                    if(igMenuItem("8-Bits .WAV")):
                        let data = history.history.historyStack[history.history.historyPointer].synthState
                        spawn(saveWav(data, 8, false))
```
And here is a part of the saveWav proc : 
```nim
proc saveWav*(data: string, bits: int = 16, sequence: bool = false): void {.gcsafe.} =
    when not defined(emscripten):
        # Some code...
    else:
        download("Hello Kurumi!")
        return
```

The download proc is the one I just posted.

**Comment by system64MC** [comment]
Also, the igBeginMenu is called in the main loop. saveWav is executed in another thread with spawn.

**Comment by yglukhov** [comment]
Well, there you have it. `download` is being called on another thread, spawned by `spawn`. Emscripten implements threads with web workers. Web workers do not have access to document, that is how JS works. Nothing to do with `jsbind`.
