### ISSUE TITLE
nimble Cannot build jsbind on my Windows system

### ISSUE THREAD

**Issue by Cleversn** [yglukhov/jsbind#2]
I'm trying to install the sound package via nimble on nim-0.15.2, and it appears to depend on jsbind, which can't build. Here is the complete output from my command prompt, Windows 7, 64-bit:

> E:\programas\nimExercs>nimble install jsbind
> Searching in "official" package list...
> Downloading https://github.com/yglukhov/jsbind into C:\Users\Clever\AppData\Loca
> l\Temp\nimble_1536\githubcom_yglukhovjsbind using git...
> Cloning into 'C:\Users\Clever\AppData\Local\Temp\nimble_1536\githubcom_yglukhovj
> sbind'...
> remote: Counting objects: 10, done.
> remote: Compressing objects: 100% (9/9), done.
> remote: Total 10 (delta 0), reused 6 (delta 0), pack-reused 0
> Unpacking objects: 100% (10/10), done.
> Installing jsbind-0.1
> Building jsbind/jsbind/emcc_wrapper_win32.exe using c backend...
> Traceback (most recent call last)
> nimble.nim(1004)         nimble
> nimble.nim(936)          doAction
> nimble.nim(580)          install
> nimble.nim(402)          installFromDir
> nimble.nim(323)          buildFromDir
> Error: unhandled exception: Build failed for package: jsbind [BuildFailed]

**Comment by yglukhov** [comment]
@Tormund, could you please take a look? That seems to be your change.

**Comment by Tormund** [comment]
@Cleversn did you properly added nim, gcc , nimble to PATH env var?

**Comment by yglukhov** [comment]
@Cleversn, could you try to `nimble install nake` for example, to see if the problem is with your environment setup?

**Comment by Cleversn** [comment]
Hi, I cannot install nake as well, same error. Perhaps there is something wrong with my setup, but the path variable appears fine, as follows:
C:\Program Files\Nim-0.15.2\bin;C:\Program Files\Nim-0.15.2\dist\mingw;C:\Program Files\Nim-0.15.2\dist\mingw\bin;C:\Users\Clever.nimble\bin

**Comment by yglukhov** [comment]
@Cleversn, please report this bug to Nim tracker. It looks a lot like installer bug. The problem is that Nim and gcc do not agree on target architecture (32/64bit).

**Comment by Cleversn** [comment]
OK, many thanks. Do you know any temporary workaround for this please?

**Comment by yglukhov** [comment]
I don't use windows so its a bit hard to suggest anything. Maybe try uninstalling Nim and reinstalling it (32bit version) along with 32bit mingw gcc. Make sure you don't have 64bit gcc on your system. Smth like that...

**Comment by Araq** [comment]
Run the 'finish.exe' program that ships with 0.15.2 and see what it tells you. It was designed to detect this very problem.

**Comment by Cleversn** [comment]
Hi, I have run finish.exe before, and it added minGW to my path successfully (see my above comment where I pasted the contents of my path variable). Also, I'm able to compile nim code normally by simply running "nim c filename.nim" from any directory. The error ocurs only when trying to install packages.

**Comment by Cleversn** [comment]
Hi, yes it's OK. I'm able to normally compile nim sources and refresh
the nimble package list from any directory at the prompt, including
other drives.

**Comment by Tormund** [comment]
@Cleversn problem with packages which has binary - nimble, jsbind(for windows), nake, rod, etc
